org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Active MDM Profile: 'dev' or 'prod'
MDM_ENV=prod

# --- DEV Profile Defaults (Local Dev / ADB Loopback / Emulator) ---
DEV_SERVER_HOST=10.0.2.2
DEV_BACKEND_PORT=8080
DEV_MQTT_PORT=1883
DEV_MQTT_TLS_PORT=8883
DEV_PORTAL_PORT=4200

# --- PROD Profile Defaults (Remote Cloud Cluster) ---
PROD_SERVER_HOST=169.58.239.251
PROD_BACKEND_PORT=8088
PROD_MQTT_PORT=1883
PROD_MQTT_TLS_PORT=8883
PROD_PORTAL_PORT=4200
